{% set name = "heavyai" %}
{% set version = "1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/heavyai-{{ version }}.tar.gz
  sha256: 1f0e22ab4c96a42eb42ba0635d0994d15a8e7709d5982abb23ef320f2fae4033

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core
  run:
    - importlib_metadata
    - numpy
    - pandas
    - pyarrow >=3.0.0
    - pyheavydb
    - python >={{ python_min }}
    - shapely

test:
  requires:
    - python {{ python_min }}
  imports:
    - heavyai

about:
  home: https://github.com/heavyai/heavyai
  summary: Data science toolkit support for HeavyDB
  dev_url: https://github.com/heavyai/heavyai
  doc_url: https://heavyai.readthedocs.io/
  license: Apache-2.0
  license_file: LICENSE.md
  description: |
    This package enables using common Python data science toolkits with
    HeavyDB. It brings dataframe support on CPU and GPU as well as
    support for arrow.

extra:
  recipe-maintainers:
    - guilhermeleobas
    - jack-mapd
    - tupui
    - pearu
